### DISCUSSION TITLE
Proposal for More Provider Customization

### DISCUSSION THREAD

**Discussion by RuinTD** [FayneAldan/lastfm-rp#36] [General]
Hello. I thought I would post this here for feedback, but I have plans to allow for more customization of where ScrobbleRP checks for both now playing **and** album art. If anyone has any better ideas, feel free to let me know!

Easiest way to explain my idea is simply with an example config:

```yaml
# Each provider will be queried in order until we find a Now Playing
scrobbleProviders:
  - service: listenbrainz
    username: RuiNtD
    # apiURL: http://localhost:8100 # Defaults to https://api.listenbrainz.org
  - service: lastfm
    username: RuiNtD
    # apiKey: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

# This is for both album art and artist art (if smallImage is set to artist)
# Each provider will be queried in order until all requested images are provided
artProviders:
  # "listening" uses the art (if any) provided by the scrobbler
  # Note that ListenBrainz doesn't provide any art
  - service: listening
  - service: musicbrainz
  - service: lastfm
    # apiKey: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
